services:
  node:
    build: .
    command: python exec_node.py
    environment:
      - LOTSONET_PORT=8468
      - BOOSTRAP_HOST=172.19.0.2
    networks:
      - lotsonet
    stdin_open: true
    tty: true

networks:
  lotsonet:
    driver: bridge
